### ISSUE TITLE
C2 Pins still connected and using thumb button

### ISSUE THREAD

**Issue by chrisistansell** [melaphor/trackzeron#1]
Wanting to code in pin C2 thumb currently tagged as `NO_PIN` so I can use the switch as `KC_SPACE` (`KC_SPC`).  Is there any way you can add this to an alternate .hex file so it functions as a space bar?

**Comment by chrisistansell** [comment]
config.h  
======
line 40
`NO_PIN `= C2

was looking at trackzeron.h could add it in as k40?

info.json
======

line 14

`{"label":k40, "x":0, "y":4},` 

trackzeron.h
============
line 31-43

```c++
#define LAYOUT( \
     k01, k02,           \
     k11, k12, k13, k14, \
     k21, k22, k23, k24, \
k30, k31, k32, k33, k34, \
k40, k41, k42, k43, k44 \
) { \
    {KC_NO, k01, k02, KC_NO, KC_NO}, \
    {KC_NO, k11, k12,   k13,   k14}, \
    {KC_NO, k21, k22,   k23,   k24}, \
    {k30,   k31, k32,   k33,   k34}, \
    {k40,   k41, k42,   k43,   k44} \
}
```

**Comment by chrisistansell** [comment]
Looking in Arduino now, looks like 12 pin needs to be added to the define list.

**Comment by melaphor** [comment]
Yes, adding it as `k40` and changing `NO_PIN` to `C2` should work.

The reason I didn't include it because I removed and chucked my whole thumb assembly when I was prototyping
